---
- name: Base | Update and Upgrade system
  apt:
    update_cache: yes
    force_apt_get: yes
    name: "*"
    state: latest
    cache_valid_time: 3600
  become: yes

- name: Base | Install base packages
  apt:
    name: 
      - htop
      - tmux
      - python3
      - python3-pip
      - python3-venv
      - nano
      - iftop
      - iotop
      - git
      - wget
      - curl
      - unzip
      - zip
    force_apt_get: yes
  become: yes

- name: Base | Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Base | Reboot if required
  reboot:
  when: reboot_required.stat.exists
  become: yes
