---
- name: Base | Update and Upgrade system
  apt:
    update_cache: yes
    force_apt_get: yes
    name: "*"
    state: latest
    cache_valid_time: 3600
  become: yes

- name: Base | Install base packages
  apt:
    name: 
      - htop
      - tmux
      - python3
      - python3-dev
      - python3-venv
      - python3-pip
      - nano
      - iftop
      - iotop
      - git
      - wget
    force_apt_get: yes
  become: yes
