---
- name: Gitea-Backup | Include required vars
  include_vars: vars.yml
  tags:
    - gitea-backup

- name: Gitea-Backup | Create directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/gitea/backups
  tags:
    - gitea-backup
  become: yes

- name: Gitea-Backup | Create backup directory in container
  command: "{{ docker_compose }} exec server mkdir -p /data/gitea/backups"
  args:
    chdir: /opt/gitea/
  tags:
    - gitea-backup

- name: Gitea-Backup | Create backup archive 
  command: "{{ docker_compose }} exec -w /data/gitea/backups server /app/gitea/gitea dump -c /data/gitea/conf/app.ini"
  args:
    chdir: /opt/gitea/
  tags:
    - gitea-backup

- name: Gitea-Backup | Get backups
  find:
    paths: /opt/gitea/backups
  register: backups
  tags:
    - gitea-backup

- name: Gitea-Backup | Fetch backup to local machine
  fetch:
    src: "{{ item.path }}"
    dest: "{{ local_backup_dir }}/{{ item.path | basename }}"
  with_items:
    - "{{ backups.files }}"
  become: yes
  tags:
    - gitea-backup

- name: Gitea-Backup | Remove remote backup
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ backups.files }}"
  become: yes
  tags:
    - gitea-backup
