---
- name: Gitea | Include required vars
  include_vars: vars.yml
  tags:
    - gitea

- name: Gitea | Create directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/gitea/
    - /opt/gitea/conf/
  tags:
    - gitea
  become: yes

- name: Gitea | Write template to file
  template:
    src: docker-compose.yml.j2
    dest: /opt/gitea/docker-compose.yml
    force: yes
  tags:
    - gitea
  become: yes

- name: Gitea | Stop gitea docker
  command: /usr/local/bin/docker-compose down
  args:
    chdir: /opt/gitea/
  tags:
    - gitea

- name: Gitea | Copy config to path
  template:
    src: app.ini.j2
    dest: /opt/gitea/gitea/gitea/conf/app.ini
    force: yes
  tags:
    - gitea
  become: yes

- name: Gitea | Start gitea docker image
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /opt/gitea/
  tags:
    - gitea
