---
- name: Nvm | Include required vars
  include_vars: vars.yml
  tags:
    - nvm

- name: Nvm | Get nvm install script
  get_url:
    url: "https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh"
    dest: "{{ NVM_TMP_DIR }}"
  tags:
    - nvm

- name: Nvm | Changing perm of nvm script
  file: 
    dest: "{{ NVM_TMP_DIR }}"
    mode: a+x
  tags:
    - nvm

- name: Nvm | Run nvm install script
  command: "{{ NVM_TMP_DIR }}"
  tags:
    - nvm

- name: Nvm | Install node
  shell: ". /home/{{ username }}/.nvm/nvm.sh install v{{ node_version }}"
  tags:
    - nvm

- name: Nvm | Install yarn
  shell: ". /home/{{ username }}/.nvm/nvm.sh && npm install -g yarn"
  become: yes
  tags:
    - nvm
