---
- name: weeapps | Include required vars
  include_vars: vars.yml

- name: weeapps | Install requirements
  shell: ". ~/.nvm/nvm.sh && yarn"
  args:
    chdir: /opt/weeapps/frontend
  environment:
    NODE_OPTIONS: "--max_old_space_size=256"

- name: weeapps | Build weeapps
  shell: ". ~/.nvm/nvm.sh && yarn build"
  args:
    chdir: /opt/weeapps/frontend
  environment:
    NODE_OPTIONS: "--max_old_space_size=256"
    BASE_URL: /weeapps
    VUE_APP_WEBSOCKET_SERVER_URL: wss://maxwittig.xyz/weeapps-server

- name: weeapps | Remove web directory
  file:
    path: "{{ web_root }}/weeapps"
    state: absent
  become: yes

- name: weeapps | Create web directory
  file:
    path: "{{ web_root }}/weeapps"
    state: directory
  become: yes

- name: weeapps | Move assets into web_dir
  shell: "mv /opt/weeapps/frontend/dist/* {{ web_root }}/weeapps"
  become: yes
