---
- name: weeapps | Include required vars
  include_vars: vars.yml
  tags:
    - weeapps
    - weeapps-server
    - weeapps-client

- name: weeapps | Clone weeapps from Github
  git:
    repo: "{{ weeapps_clone_url }}"
    dest: /opt/weeapps/
    update: yes
    clone: yes
    force: yes
  become: yes
  tags:
    - weeapps
    - weeapps-server
    - weeapps-client

- name: weeapps | Change owner of directory
  file:
    state: directory
    path: /opt/weeapps/
    recurse: yes
    owner: "{{ username }}"
  become: yes
  tags:
    - weeapps
    - weeapps-server
    - weeapps-client

- name: weeapps | Import client
  import_tasks: client.yml
  tags:
    - weeapps
    - weeapps-client

- name: weeapps | Import server
  import_tasks: server.yml
  tags:
    - weeapps
    - weeapps-server
