---
- name: weeapps | Include required vars
  include_vars: vars.yml

- name: weeapps | Write template to file
  template:
    src: docker-compose.yml.j2
    dest: /opt/weeapps/backend/docker-compose.yml
    force: yes
  become: yes

- name: weeapps | Stop weeapps docker
  command: "{{ docker_compose }} down --remove-orphans"
  args:
    chdir: /opt/weeapps/backend/

- name: weeapps | Pull images
  command: "{{ docker_compose }} pull"
  args:
    chdir: /opt/weeapps/backend/

- name: weeapps | Start weeapps docker image
  command: "{{ docker_compose }} up --build -d --force-recreate"
  args:
    chdir: /opt/weeapps/backend/
