---
- name: Link Shortener | Clone link shortener from GitHub
  git:
    repo: https://github.com/max-wittig/link-shortener.git
    dest: /opt/link-shortener
    update: yes
    clone: yes
  become: yes

- name: Link Shortener | Build docker image
  docker_image:
    source: build
    build:
      nocache: yes
      path: /opt/link-shortener
      pull: yes
    name: link-shortener

- name: Link Shortener | Run docker image
  docker_container:
    name: link-shortener
    image: link-shortener
    restart_policy: "always"
    exposed_ports: "5000"
    published_ports: 5000:5000
    detach: "true"
    env:
      BASE_URL: "/short"
