---
- name: Link Shortener | Clone link shortener from GitHub
  git:
    repo: https://github.com/max-wittig/link_shortener.git
    dest: /opt/link_shortener
    update: yes
    clone: yes
  become: yes

- name: Link Shortener | Build docker image
  docker_image:
    nocache: "true"
    path: /opt/link_shortener
    name: link_shortener
    force: "true"

- name: Link Shortener | Run docker image
  docker_container:
    name: link_shortener
    image: link_shortener
    restart_policy: "always"
    exposed_ports: "5000"
    published_ports: 5000:5000
    detach: "true"
