---
- name: LunchBot | Include required vars
  include_vars: vars.yml

- name: LunchBot | Clone from GitHub
  git:
    repo: https://github.com/max-wittig/LunchBot.git
    dest: /opt/lunchbot
    update: yes
    clone: yes
  become: yes
  register: git_cloned

- name: LunchBot | Build docker image
  docker_image:
    source: build
    build:
      nocache: yes
      path: /opt/lunchbot
      pull: yes
    name: lunchbot
    force_source: yes
  when: git_cloned.changed

- name: LunchBot | Run docker image
  docker_container:
    name: lunchbot
    image: lunchbot
    restart_policy: "always"
    detach: yes
    env:
      CLIENT_ID: "{{ lunchbot.client_id }}"
      CLIENT_SECRET: "{{ lunchbot.client_secret }}"
      CONVERSATION_ID: "{{ lunchbot.conversation_id }}"
