---
- name: MyApplications | Create opt dir
  file:
    path: /opt
    state: directory
  become: yes
  tags:
    - myapplications

- name: MyApplications | Import Link Shortener
  import_tasks: link_shortener.yml
  tags:
    - link-shortener
    - myapplications

- name: MyApplications | Import Steam Games Viewer
  import_tasks: steam_games_viewer.yml
  tags:
    - steamgamesviewer
    - myapplications

- name: MyApplications | Import Startpage
  import_tasks: startpage.yml
  tags:
    - startpage
    - myapplications

- name: MyApplications | Import Gitea-Mirror
  import_tasks: gitea_mirror.yml
  tags:
    - gitea-mirror
    - myapplications
