---
- name: NodeApps | Clone Nodeapps from GitHub
  git:
    repo: https://github.com/max-wittig/NodeApps.git
    dest: /opt/nodeapps
    update: yes
    clone: yes
  become: yes
  register: git_cloned

- name: NodeApps | Build docker image
  docker_image:
    source: build
    build:
      nocache: yes
      path: /opt/nodeapps
      pull: yes
    name: nodeapps
    force_source: yes
  when: git_cloned.changed

- name: NodeApps | Run docker image
  docker_container:
    name: nodeapps
    image: nodeapps
    exposed_ports: "3000"
    published_ports: 3000:3000
    detach: yes
