---
- name: Startpage | Include required vars
  include_vars: vars.yml

- name: Startpage | Clone startpage from Github
  git:
    repo: "{{ startpage_clone_url }}"
    dest: /opt/startpage
    update: yes
    clone: yes
    force: yes
  become: yes
  register: git_cloned

- name: Startpage | Change owner of directory
  file:
    state: directory
    path: /opt/startpage
    recurse: yes
    owner: "{{ username }}"
  become: yes
  when: git_cloned.changed

- name: Startpage | Install requirements
  shell: ". ~/.nvm/nvm.sh && yarn"
  args:
    chdir: /opt/startpage
  environment:
    NODE_OPTIONS: "--max_old_space_size=256"
  when: git_cloned.changed

- name: Startpage | Build startpage
  shell: ". ~/.nvm/nvm.sh && yarn build"
  args:
    chdir: /opt/startpage
  environment:
    NODE_OPTIONS: "--max_old_space_size=256"
  when: git_cloned.changed

- name: Startpage | Copy assets into web_dir
  shell: "cp -r /opt/startpage/dist/* {{ web_root }}/"
  become: yes
  when: git_cloned.changed
