---
# this requires gitea to be setup, will be on GitHub once project is done
- name: unnamed | Include required vars
  include_vars: vars.yml

- name: unnamed | Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/unnamed/
  become: yes

- name: unnamed | Clone unnamed from Gitea
  git:
    repo: "{{ unnamed_client_clone_url }}"
    dest: /opt/unnamed/client
    update: yes
    clone: yes
    force: yes
  become: yes

- name: unnamed | Change owner of directory
  file:
    state: directory
    path: /opt/unnamed/client
    recurse: yes
    owner: "{{ username }}"
  become: yes

- name: unnamed | Build docker image
  docker_image:
    source: build
    build:
      nocache: yes
      path: /opt/unnamed/client/
      pull: yes
    name: unnamed
    force_source: yes

- name: unnamed | Run docker image
  docker_container:
    name: unnamed
    image: unnamed
    published_ports: 7600:8080
    detach: yes
    env:
      BASE_URL: /unnamed/
      VUE_APP_WEBSOCKET_SERVER_URL: wss://maxwittig.xyz/unnamed-server

- name: unnamed | Remove web directory
  file:
    path: "{{ web_root }}/unnamed"
    state: absent
  become: yes
