---
- name: Docker | Make data docker dir
  file:
    path: /mnt/data/docker
    state: directory
  become: yes
  tags:
    - docker

- name: Docker | Install docker dependencies
  become: yes
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    force_apt_get: yes
  tags:
    - docker

- name: Docker | Install ansible pip docker dependencies
  pip:
    name:
      - docker
  tags:
    - docker

- name: Docker | Add docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker

- name: Docker | Add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge
    state: present
  tags:
    - docker

- name: Docker | Install docker-ce
  become: yes
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
    install_recommends: no
  tags:
    - docker

- name: Docker | Modify data dir
  lineinfile: 
    dest: /lib/systemd/system/docker.service
    regexp: "^ExecStart="
    line: "ExecStart=/usr/bin/dockerd -g /mnt/data/docker -H fd:// --containerd=/run/containerd/containerd.sock"
    state: present
  register: data_dir
  become: yes
  tags:
    - docker

- name: Docker | Restart daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: data_dir.changed
  tags:
    - docker

- name: Docker | Import docker-compose tasks
  import_tasks: install-docker-compose.yml
  tags:
    - docker-compose
    - docker

- name: Docker | Prune all images
  command: docker system prune -a -f
  tags:
    - docker
