---
- name: Docker | Install docker dependencies
  become: yes
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - docker

- name: Docker | Install pip docker dependencies
  pip:
    name:
      - docker
  tags:
    - docker

- name: Docker | Add docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker

- name: Docker | Add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge
    state: present
  tags:
    - docker

- name: Docker | Install docker-ce
  become: yes
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
    install_recommends: no
  tags:
    - docker

- name: Docker | Import docker-compose tasks
  import_tasks: install-docker-compose.yml
  tags:
    - docker-compose
    - docker
